spring:
  h2:
    console:
      enabled: true
      path: /h2-ui

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
  main:
    allow-bean-definition-overriding: true
      
